### ISSUE TITLE
Cannot use hooks inside SimpleStateConsumer function

### ISSUE THREAD

**Issue by cuddeford** [Jahans3/use-simple-state#12]
React throws an error and tells me the hook call is invalid. "Hooks can only be called inside the body of a function component".

I'd like to use the dispatch method inside the body of a SimpleStateConsumer based on the subscribed state which I assumed was the intended design. It is possible to do, just not with any hooks which makes it difficult to do any complex logic. Am I missing something or is there a fundamental limitation at play? Surely the function is also a function component because it returns JSX?

### Example
```javascript
import { reloadCustomer } from '../server'

...

const mapState = ({ reloadTime, customer }) => ({ reloadTime, customer })
return (
  <SimpleStateConsumer mapState={mapState}>
    {({ state, dispatch }) => {
      useEffect(() => {
        reloadCustomer(dispatch)
      }, [reloadTime])

      return <Customer customer={state.customer} />
    }}
  </SimpleStateConsumer>
)
```

**Comment by Jahans3** [comment]
Hey @cuddeford apologies for the late reply, haven't been too active the past year. I assume you've sorted your issue, but I'll answer it anyway in case someone comes across the same issue:

I can see how the wording of the error from React would make this seem confusing, since you are indeed using your hooks inside the body of a function component. The issue here is the function component inside `SimpleStateConsumer` is being defined in-line.

A solution here could be to just pass dispatch into `Customer` and run your hooks there:

```javascript
function Customer({ customer, reloadTime, dispatch }) {
   useEffect(() => {
         reloadCustomer(dispatch)
   }, [reloadTime]);

  return ...
}
```

FYI - with the announcement of `React.useContextSelector` this will be a thing of the past and I will be incorporating it into this library, so we can finally move to a full hooks-based solution without impacting performance and I will also remove `SimpleStateConsumer`.
