### ISSUE TITLE
Using dispatch from outside of a React component

### ISSUE THREAD

**Issue by cuddeford** [Jahans3/use-simple-state#13]
In my particular case I want to perform server authentication and store the result of the login in state but I can't call `dispatch` unless I'm inside a React component. If I remember correctly this is possible in Redux.

Are there any ways of doing this or am I forced to wrap my server login in a React component?

**Comment by Jahans3** [comment]
Unfortunately since this isn't decoupled from React like Redux is this isn't possible. In order to work around this issue I've built in functionality similar to `redux-thunk` that allows you to pass functions as actions, when you do this you will receive `state` and `dispatch` as params in the second function, like so:

```javascript
const someAction = (yourCustomParams) => async (state, dispatch) => {
  const result = await api.someApi(yourCustomParams);
  dispatch(something);
};
```
Note: it doesn't have to be an async function, but it usually makes sense in these cases.

There's a fully-fleshed out example in the docs: https://github.com/Jahans3/use-simple-state#async-actions
