### ISSUE TITLE
How is it different from useState + useContext?

### ISSUE THREAD

**Issue by Skona27** [Jahans3/use-simple-state#8]
Hi! 

I have got a question. Your library looks really like redux, but similar effect can be achieved by using `useState` and `useContext` hooks. Are there some benefits that one can get from using your solution :smiley: ?

**Comment by Jahans3** [comment]
Hi, sure there are some advantages but you should consider each project's needs on a case by case basis. Some of the key advantages of using this over `useState` + `useContext` would be:

* Partially subscribing to global state - this is arguably the main reason for using a library as without this your app will noticeably suffer from performance issues due to the fact that when any part of the state updates every connected component will re-render. See this: https://github.com/Jahans3/use-simple-state#caveat and also this: https://github.com/Jahans3/use-simple-state/issues/7
* Following on from the above, we will be moving store *state* out of context due to context not being suitable for Flux-like state propagation and because our main hook should also have the same performance benefits as `SimpleStateConsumer`. See this quote from Seb Markbage: https://github.com/facebook/react/issues/14110#issuecomment-448074060
* Asynchronous actions: https://github.com/Jahans3/use-simple-state#async-actions
* `mapState`/`mapDispatch`: https://github.com/Jahans3/use-simple-state#simplestateconsumer
* No need to reinvent the wheel for each project
* `useState` - means you don't have to worry about implementing state update logic on `setState` calls or writing a wrapper for `setState` (if you are creating your own state container I'd recommend sticking with `useReducer`)

There's no silver bullet for state management. A custom solution might seem like less work at first but has noticeable performance issues and may not be suitable for large or complex apps for a few reasons. Similarly, using Redux may also seem unnecessary on smaller projects and if you don't need to leverage the advanced features or large ecosystem it's likely you don't need Redux at all. There's lots of libraries out there to choose from, I'd recommend checking a few out to see what best fits your needs.

When deciding between a custom solution, this library or Redux a general rule of thumb I like to follow is:
* Do you anticipate your app will grow large with complex state? Do you want advanced Redux features like action batching? Go with Redux
* Is your app small with minimal, simple global state? Is performance not an issue? A custom solution may work
* Something in-between the above? Go with a library like this

**Comment by Skona27** [comment]
Thanks for your comprehensive anwser. I'll definitely give this a try!
